Repository terraform-google-modules/terraform-google-project-factory, pull requests merged in 2019-06, with the labels that each got.

#225 upgrade to terraform 0.12
  Gemfile
  Gemfile.lock
  examples/gke_shared_vpc/main.tf
  examples/gke_shared_vpc/variables.tf
  examples/group_project/main.tf
  examples/group_project/outputs.tf
  examples/group_project/variables.tf
  examples/project-hierarchy/main.tf
  examples/project-hierarchy/outputs.tf
  examples/project-hierarchy/variables.tf
  examples/shared_vpc/main.tf
  examples/shared_vpc/outputs.tf
  examples/shared_vpc/variables.tf
  examples/simple_project/main.tf
  examples/simple_project/outputs.tf
  examples/simple_project/variables.tf
  main.tf
  modules/app_engine/main.tf
  modules/app_engine/outputs.tf
  modules/app_engine/variables.tf
  modules/core_project_factory/main.tf
  modules/core_project_factory/outputs.tf
  modules/core_project_factory/variables.tf
  modules/fabric-project/main.tf
  modules/fabric-project/outputs.tf
  modules/fabric-project/variables.tf
  modules/gsuite_enabled/main.tf
  modules/gsuite_enabled/outputs.tf
  modules/gsuite_enabled/variables.tf
  modules/gsuite_group/main.tf
  modules/gsuite_group/outputs.tf
  modules/gsuite_group/variables.tf
  modules/project_services/examples/project_services/main.tf
  modules/project_services/examples/project_services/outputs.tf
  modules/project_services/examples/project_services/variables.tf
  modules/project_services/main.tf
  modules/project_services/outputs.tf
  modules/project_services/variables.tf
  outputs.tf
  test/fixtures/minimal/main.tf
  test/fixtures/shared/outputs.tf
  test/fixtures/shared/variables.tf
  test/fixtures/shared_vpc_no_subnets/extra_variables.tf
  test/fixtures/shared_vpc_no_subnets/main.tf
  variables.tf
Labels: blocked-0.12, enhancement

#231 app_engine example fixed with upgrade to 0.12 terraform
  examples/app_engine/main.tf
  examples/app_engine/outputs.tf
  examples/app_engine/variables.tf
Labels: blocked-0.12, enhancement

#234 Add `project_services_authority` to `project_id`
  modules/core_project_factory/outputs.tf
  modules/gsuite_enabled/variables.tf
Labels: bug

#236 Fixed doc generator
  README.md
  examples/app_engine/README.md
  examples/gke_shared_vpc/README.md
  examples/group_project/README.md
  examples/project-hierarchy/README.md
  examples/shared_vpc/README.md
  examples/simple_project/README.md
  helpers/combine_docfiles.py
  modules/fabric-project/README.md
  modules/gsuite_enabled/README.md
  modules/project_services/README.md
  modules/project_services/examples/project_services/README.md
  test/fixtures/full/README.md
  test/fixtures/minimal/README.md
  test/make.sh
Labels: enhancement
