Repository terraform-google-modules/terraform-google-project-factory, pull requests merged in 2019-11, with the labels that each got.

#310 Update changelog for v5.0.0, add migration doc for fabric-project
  CHANGELOG.md
  docs/upgrading_to_fabric_project_v5.0.md
Labels: enhancement

#311 Fix module crash on empty api list
  modules/project_services/outputs.tf
Labels: bug

#295 Script Helper Update
  helpers/setup-sa.sh
Labels: bug, enhancement

#304 Fixed precondition script to run on win
  README.md
  main.tf
  modules/core_project_factory/locals.tf
  modules/core_project_factory/main.tf
  modules/core_project_factory/variables.tf
  modules/gsuite_enabled/README.md
  modules/gsuite_enabled/main.tf
  modules/gsuite_enabled/variables.tf
  modules/shared_vpc/main.tf
  modules/shared_vpc/variables.tf
  variables.tf
Labels: bug
